### ISSUE TITLE
Mu importer error

### ISSUE THREAD

**Issue by emab123** [Dasoccerguy/io_kspblender#14]
Hey, before I start talking about all the errors I would like to congratulate what seems to be a very useful code for someone like me, who has a 3d printer and would love to 3d print kerbal crafts. 
Now for the errors. The issue happens when I try to import a craft directly from ksp ships folder. The following error messages appears on blender:

--------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "C:\Users\eric\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_object_mu-master\import_craft.py", line 278, in execute
    return import_craft_op(self, context, **keywords)
  File "C:\Users\eric\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_object_mu-master\import_craft.py", line 250, in import_craft_op
    create_db()
  File "C:\Users\eric\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_object_mu-master\import_craft.py", line 216, in create_db
    recurse_tree(gamedata, build_db)
  File "C:\Users\eric\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_object_mu-master\import_craft.py", line 171, in recurse_tree
    files = os.listdir(path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/home/bill/ksp/KSP_linux-ckan/GameData'

location: <unknown location>:-1

--------------------------------------------------------------------------------------------------------------

So can you help me? I have absolutely no idea how this kind of coding works...

**Comment by Demannu** [comment]
Hi there,

I just discovered this issue as well. What you need to do is open 
`C:\Users\eric\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_object_mu-master\import_craft.py` and do a search for `/home/bill` and replace the entire string with the full location of your KSP directory.

However, I am still experiencing some other issues preventing me from using this software.

-Demannu
