### ISSUE TITLE
Cannot import craft files.

### ISSUE THREAD

**Issue by Telekmac** [Dasoccerguy/io_kspblender#18]
When trying to import a craft file i get this error. I'm not sure what to do. Any help appreciated!

Traceback (most recent call last):
  File "C:\Users\telek\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_kspblender-master\__init__.py", line 59, in execute
    return import_craft.import_craft(self,context,**keywords)
  File "C:\Users\telek\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_kspblender-master\import_craft.py", line 61, in import_craft
    [partdir,right_location] = part_dict.make_dict(ksp)             # <3 Cptman
  File "C:\Users\telek\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_kspblender-master\part_dict.py", line 43, in make_dict
    p,rl = make_dict_aux(cfgs,path)
  File "C:\Users\telek\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_kspblender-master\part_dict.py", line 95, in make_dict_aux
    for line in f: #Looks for the name,scale,... in a .cfg
  File "C:\Users\telek\OneDrive\Desktop\blender-2.79.0-git.001414fb2f73-windows64\2.79\python\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 5: invalid start byte

location: <unknown location>:-1

**Comment by dogevspenguin** [comment]
You are different than me a little https://ibb.co/jvHD63g

**Comment by galaxyentity904** [comment]
> You are different than me a little https://ibb.co/jvHD63g

I am having the same issue as this person
Importing .mu files works but not .craft files

Details:
Xubuntu 20.10
Blender 2.92.0
Ksp 1.11.0
I have kspdir.txt set to:
```
/home/(me)/.steam/debian-installation/steamapps/Kerbal Space Program/GameData/
```
@dogevspenguin do you have similar settings? Details would be appreciated

**Comment by galaxyentity904** [comment]
> > You are different than me a little https://ibb.co/jvHD63g
> 
> I am having the same issue as this person
> Importing .mu files works but not .craft files
> 
> Details:
> Xubuntu 20.10
> Blender 2.92.0
> Ksp 1.11.0
> I have kspdir.txt set to:
> ```
> /home/(me)/.steam/debian-installation/steamapps/Kerbal Space Program/GameData/
> ```
> @dogevspenguin do you have similar settings? Details would be appreciated

Addition:
It appears io_object_mu is being used to import the .craft file, but I'm trying to use io_KSPBlender because io_object_mu's import appears broken. How do I use io_KSPBlender instead? @dogevspenguin this seems to be your issue as well
