### ISSUE TITLE
UnicodeDecodeError importing .craft file

### ISSUE THREAD

**Issue by kristjan** [Dasoccerguy/io_kspblender#3]
I've followed the README directions, but get the following stack trace trying to import a craft:

```
Traceback (most recent call last):
  File "/Applications/blender.app/Contents/Resources/2.75/scripts/addons/io_kspblender-master/__init__.py", line 59, in execute
    return import_craft.import_craft(self,context,**keywords)
  File "/Applications/blender.app/Contents/Resources/2.75/scripts/addons/io_kspblender-master/import_craft.py", line 61, in execute
    [partdir,right_location] = part_dict.make_dict(ksp)     # <3 Cptman
  File "/Applications/blender.app/Contents/Resources/2.75/scripts/addons/io_kspblender-master/part_dict.py", line 43, in execute
    p.rl = make_dict_aux(cfgs.path)
  File "/Applications/blender.app/Contents/Resources/2.75/scripts/addons/io_kspblender-master/part_dict.py", line 95, in execute
    for line in f: #Looks for the name,scale,... in a .cfg
  For "/Applications/blender.app/Contents/MacOS/../Resources/2.75/python/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)

  location: <unknown location>:-1
```

Any guidance?

**Comment by spencerarrasmith** [comment]
Hey Kristján,

It might be because of the accents in your name. I haven't ever tried it
with non-English letters like ø in the file path. I thought I had accounted
for that by reading things in Unicode as opposed to ASCII, but evidently
not.

I'd be happy to try some things and see if we can get it to work. I live in
the US (GMT -6), so if you're in Europe it might be tough to find a time we
can both be online at the same time. Worst case we can just reply every
couple of hours.

Tomorrow at 10pm my time (4am GMT) I'll take a look. Thanks for sharing the
bug!

**Comment by kristjan** [comment]
Hah, for once that didn't occur to me - really good theory. I don't think I stuck any accents into KSP, but I'll look around. Is there any indication where it might be finding one? Maybe it's pulling something out of the OS?

Speaking of OS, in case versioning is helpful at all:
- OSX 10.10.5
- Blender 2.75
- KSP 1.04

**Comment by DanilaFe** [comment]
~~Yo I just wanted to say that I was experiencing it too, and while trying to find the issue i added line~~

``` python
print(os.path.join(path,cfg))
```

~~right before the line~~

``` python
f=open(...)
```

~~in the make_dict_aux function. (part_dict.py)~~
~~And then it started working. Probably not a proper solution, but something happened.~~

EDIT

As a follow up, running through terminal is what fixed the issue, not the line. Sorry!

**Comment by ZuChen93** [comment]
I met the same problem. My UnicodeDecodeError is:  'gbk' codec.
I am a Chinese user. My Game Location is "D:\Game\Steam\steamapps\common\Kerbal Space Program".
I don't know the 'gbk' indicate which file, the Python files, or the games files?

**Comment by rustymyers** [comment]
I'm receiving this same error message when trying to import a craft file. 
Following all the instructions, except that the add ons are placed in my home instead of the app:
"/Users/rzm102/Library/Application Support/Blender/2.76/scripts/addons/io_kspblender-master"
Made sure the path to my KSP dir was placed in kspdir.txt:
"/Applications/KSP_osx"

Currently running OS X 10.11.3.

Can't figure out what's going wrong here, but willing to troubleshoot.
Thanks

**Comment by spencerarrasmith** [comment]
Everyone's probably noticed by now that I've been neglecting this project. I keep telling myself I'll get back into it but I keep procrastinating. Hopefully sometime this week I'll take a stab at some of these errors people are reporting, or at least code in better error reporting so we all have an easier time figuring out what's wrong.
