### ISSUE TITLE
IndexOutOfBounds error when importing Struts. 

### ISSUE THREAD

**Issue by DanilaFe** [Dasoccerguy/io_kspblender#4]
Hi!
I've just set up this tool, and i'm having trouble importing Crafts which have struts.
Before I begin, specs:
OS - Mac OS X Yosemite
Blender Version - 2.75a
KSPBlender version - latest, using git clone.

I have a full log from the Terminal output, but here's the gist:

```
Traceback (most recent call last):
  File "/Users/danila/Downloads/Blender/Blender.app/Contents/Resources/2.75/scripts/addons/io_kspblender-master/__init__.py", line 60, in execute
    return import_craft.import_craft(self,context,**keywords)
  File "/Users/danila/Downloads/Blender/Blender.app/Contents/Resources/2.75/scripts/addons/io_kspblender-master/import_craft.py", line 63, in import_craft
    craft = import_parts(filepath,partdir,rightscale,right_location)
  File "/Users/danila/Downloads/Blender/Blender.app/Contents/Resources/2.75/scripts/addons/io_kspblender-master/import_craft.py", line 200, in import_parts
    add_strut(part,objlist)
  File "/Users/danila/Downloads/Blender/Blender.app/Contents/Resources/2.75/scripts/addons/io_kspblender-master/import_craft.py", line 366, in add_strut
    newstrut.data.vertices[7].co.y = strutlen
IndexError: bpy_prop_collection[index]: index 7 out of range, size 7
```

Any idea what it could be?

**Comment by spencerarrasmith** [comment]
Hey Danila

Could you send me the ship that's giving you that error? Maybe I can make
some sense of it that way.

My plugin is about 3 months out of date now, so I'm not surprised to see
errors. I've just been too lazy/busy to fix it.

**Comment by DanilaFe** [comment]
Sure!
Here's a [filedropper link](http://www.filedropper.com/moonrescuelandermk2).
It's all stock.

**Comment by bryan-lunt** [comment]
I get the same issue on my ships with struts.

**Comment by DanilaFe** [comment]
This so certainly an issue with struts, at least as far as I could tell from examining the lines that throw the error.
