### ISSUE TITLE
IndexError when using pretty much any menu function

### ISSUE THREAD

**Issue by unlimitedbacon** [Dasoccerguy/io_kspblender#5]
```
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/usr/share/blender/2.75/scripts/modules/bpy/ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "/home/tyler/.config/blender/2.75/scripts/addons/io_kspblender-master/__init__.py", line 72, in execute
    shippart = selected.pop(0)
IndexError: pop from empty list

location: /usr/share/blender/2.75/scripts/modules/bpy/ops.py:189
```

I get this when using any of the following K menu items:
- Select Ship
- Select Stage
- Make One Mesh
- Make 3D Printable

Blender 2.75a on Arch Linux. KSP 1.0.4. Stock Kerbal X craft.

**Comment by spencerarrasmith** [comment]
Thanks for the report. To use those functions, you have to first select one part of the relevant ship. If you have nothing selected, it will try to pop from an empty list and apparently throw that error.

I'll be doing a big update sometime next 2 weeks and I'll be sure to address this issue.

**Comment by unlimitedbacon** [comment]
That makes sense. I thought I had tried with an object selected, but apparently not.
